// Auto-generated fallback data from the latest sheet response
export const INITIAL_MEMBERS = [
  {
    "id": "101",
    "name": "Sanat Sikhar Sinha",
    "team": "Secretariat",
    "designation": "Member",
    "email": "",
    "phone": "",
    "linkedin": "",
    "instagram": "",
    "branch": "—",
    "year": "",
    "regNo": "—",
    "dob": "",
    "photo": ""
  },
  {
    "id": "105",
    "name": "Subham Panda",
    "team": "Event management",
    "designation": "Lead",
    "email": "subhampanda1000@gmail.com",
    "phone": "8280651536",
    "linkedin": "https://www.linkedin.com/in/subham-panda-764a69293?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "subham_panda04",
    "branch": "CSE",
    "year": "4th year",
    "regNo": "2341016100",
    "dob": "10/10/2004",
    "photo": "https://drive.google.com/thumbnail?id=1e0lZ3PazWyGfIG3ZjjvPPwLoPzZLNvtA&sz=w1000"
  },
  {
    "id": "106",
    "name": "Parminder Singh",
    "team": "Event management",
    "designation": "Core",
    "email": "singh.sanjam18@gmail.com",
    "phone": "6203023719",
    "linkedin": "https://www.linkedin.com/in/parminder-singh-a22710268?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "_singh.18",
    "branch": "Cse",
    "year": "3rd year",
    "regNo": "24E119E11",
    "dob": "7/20/2026",
    "photo": "https://drive.google.com/thumbnail?id=1rwA7IFV-xGN_HQL1OuWtWNAEZ1fpbRSt&sz=w1000"
  },
  {
    "id": "107",
    "name": "Saranya Dash",
    "team": "Content, Design",
    "designation": "Core",
    "email": "dashsaranya.soa@gmail.com",
    "phone": "9124648155",
    "linkedin": "https://www.linkedin.com/in/saranya-dash-aa491a375?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/just_a_birkin?stkn=MWdmdDRlYXFidHNmOQ==",
    "branch": "Btech Cse core",
    "year": "2nd year",
    "regNo": "25E104B47",
    "dob": "8/26/2007",
    "photo": "https://drive.google.com/thumbnail?id=1yFnax_1t8ozqEJVSM2cWifWI_37F9gGL&sz=w1000"
  },
  {
    "id": "108",
    "name": "Neelesh Kumar Behera",
    "team": "Media",
    "designation": "Core",
    "email": "neeleshbehera81@gmail.com",
    "phone": "8984555935",
    "linkedin": "https://www.linkedin.com/in/neelesh-kumar-behera-2183433b3?utm_source=share_via&utm_content=profile&utm_medium=member_ios",
    "instagram": "https://www.instagram.com/_.neelesh._.nkb._?stkn=MTY2ejloMjI1ajJ1OA%3D%3D&utm_source=qr",
    "branch": "B.tech CSE",
    "year": "3rd year",
    "regNo": "24E102A82",
    "dob": "8/8/2006",
    "photo": "https://drive.google.com/thumbnail?id=1nG_2XYFI0T4cs2MpRXSgqoLlQbxhOqSu&sz=w1000"
  },
  {
    "id": "109",
    "name": "Rohit Mukhi",
    "team": "Content",
    "designation": "Core",
    "email": "rohitmukhi52@gmail.com",
    "phone": "8580371372",
    "linkedin": "https://www.linkedin.com/in/rohit-mukhi-009a14263?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "rohit__mukhi",
    "branch": "CSE",
    "year": "4th year",
    "regNo": "2341013419",
    "dob": "6/30/2003",
    "photo": "https://drive.google.com/thumbnail?id=1ZX_DLTMVpIBIATmwhMRDXeWEDVp8nXHX&sz=w1000"
  },
  {
    "id": "110",
    "name": "Kalyan Jyoti Mishra",
    "team": "Event management",
    "designation": "Core",
    "email": "kalyanjyotimishra@gmail.com",
    "phone": "7682953323",
    "linkedin": "https://www.linkedin.com/in/kalyan-jyoti-mishra",
    "instagram": "https://www.instagram.com/onlyonekalyan?stkn=MWZtcWw2ZHZ1NmNzOQ==",
    "branch": "Data science",
    "year": "2nd year",
    "regNo": "25E113B78",
    "dob": "7/22/2007",
    "photo": "https://drive.google.com/thumbnail?id=1HQ_eLIrAmMmc9D9h_gKi1LuyPAZagYJT&sz=w1000"
  },
  {
    "id": "111",
    "name": "Spandan Pattanaik",
    "team": "Public relation",
    "designation": "Core",
    "email": "spandanpattanaik2007@gmail.com",
    "phone": "7978667994",
    "linkedin": "https://www.linkedin.com/in/spandan-pattanaik-032b201b4?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/spandan__pattanaik?stkn=eHc0OGJwdTRqNHhy",
    "branch": "CSE CORE",
    "year": "3rd year",
    "regNo": "24E116C39",
    "dob": "2/5/2007",
    "photo": "https://drive.google.com/thumbnail?id=1V4Qlsh5UVPJtDefIdj2vqF_7dNwzR_rh&sz=w1000"
  },
  {
    "id": "112",
    "name": "Utkarsh Sinha",
    "team": "Technical",
    "designation": "Core",
    "email": "sinhau65@gmail.com",
    "phone": "9142195378",
    "linkedin": "www.linkedin.com/in/utkarshhhsinha",
    "instagram": "https://www.instagram.com/my.utkarshhh/",
    "branch": "Btech Cse (AI/ML)",
    "year": "3rd year",
    "regNo": "24E119E33",
    "dob": "6/5/2005",
    "photo": "https://drive.google.com/thumbnail?id=1EYmqJMbVLcKnqOejLGalxbA5i9AUrYA2&sz=w1000"
  },
  {
    "id": "113",
    "name": "Rajeev Pramanik",
    "team": "Technical",
    "designation": "Core",
    "email": "imrajeev20@gmail.com",
    "phone": "8789850340",
    "linkedin": "https://www.linkedin.com/in/rajeev-pramanik-248105331?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "rajeev.pramanik18",
    "branch": "CSE(AIML)",
    "year": "2nd year",
    "regNo": "25E116D72",
    "dob": "8/20/2004",
    "photo": "https://drive.google.com/thumbnail?id=1vOCvaX9JRKrcn6TRaVa8_mkU8AynFaOu&sz=w1000"
  },
  {
    "id": "114",
    "name": "Sujay Jagat",
    "team": "Technical",
    "designation": "Lead",
    "email": "sjagat222@gmail.com",
    "phone": "7004577714",
    "linkedin": "https://www.linkedin.com/in/sujay-jagat-7ab37b32a?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/sujay.jagat?stkn=MXM4N2RxOWpzajNpeA==",
    "branch": "CSE CORE",
    "year": "3rd year",
    "regNo": "24E110A82",
    "dob": "11/24/2005",
    "photo": "https://drive.google.com/thumbnail?id=1pAXkPS5RkZqRDJ2aYk5KLIANCx5Mot-J&sz=w1000"
  },
  {
    "id": "115",
    "name": "D.Amarnath Patro",
    "team": "Public relation",
    "designation": "Core",
    "email": "amarpatro25@gmail.com",
    "phone": "9861422119",
    "linkedin": "https://www.linkedin.com/in/amarnathpatro/",
    "instagram": "https://www.instagram.com/amar_the_one?stkn=MXFob3R4dHY5aXVsZQ==",
    "branch": "CSE(CYSEC)",
    "year": "3rd year",
    "regNo": "24E116C27",
    "dob": "8/31/2006",
    "photo": "https://drive.google.com/thumbnail?id=15iZ5z3tBMvwaAtpjOoQiSchriAc6l22i&sz=w1000"
  },
  {
    "id": "116",
    "name": "Rohit Kumar",
    "team": "Technical",
    "designation": "Co-Lead",
    "email": "rohit983527@gmail.com",
    "phone": "9835279029",
    "linkedin": "https://www.linkedin.com/in/rohit-kumar-238b26316/",
    "instagram": "https://www.instagram.com/_rohit__kumar_98/",
    "branch": "C.S.E (Core)",
    "year": "3rd year",
    "regNo": "24E111B55",
    "dob": "3/18/2006",
    "photo": "https://drive.google.com/thumbnail?id=1zx-4F844SyChJ3u-gm84s1gi6oLjVSuy&sz=w1000"
  },
  {
    "id": "117",
    "name": "Ayush Kumar Singh",
    "team": "Public relation",
    "designation": "Core",
    "email": "s14ayush@gmail.com",
    "phone": "9508904992",
    "linkedin": "https://www.linkedin.com/in/theayush17",
    "instagram": "https://www.instagram.com/theayush_17",
    "branch": "CSE",
    "year": "4th year",
    "regNo": "2341019478",
    "dob": "2/17/2005",
    "photo": "https://drive.google.com/thumbnail?id=1oAPmCI7TPsBmv4QkLLEAXOcoN-o5xb8h&sz=w1000"
  },
  {
    "id": "118",
    "name": "Rishit Swain",
    "team": "Public relation",
    "designation": "Core",
    "email": "rajashreeswain471@gmail.com",
    "phone": "7735776647",
    "linkedin": "https://www.linkedin.com/in/rishit-swain-252768376?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "NA",
    "branch": "CSE(CYSC)",
    "year": "3rd year",
    "regNo": "24E119F02",
    "dob": "9/1/2006",
    "photo": "https://drive.google.com/thumbnail?id=1asVVTc3YREIDdIW5tJBlv1YNMaGAIaNy&sz=w1000"
  },
  {
    "id": "119",
    "name": "Shruti Mohanty",
    "team": "Event management",
    "designation": "Core",
    "email": "shrutimohanty911@gmail.com",
    "phone": "7848094794",
    "linkedin": "https://www.linkedin.com/in/shruti-mohanty-44418b3a3?utm_source=share_via&utm_content=profile&utm_medium=member_android",
    "instagram": "https://www.instagram.com/itsshruti_06?stkn=MWo2aXU5ODJjZzRhaw==",
    "branch": "Btech CSE",
    "year": "3rd year",
    "regNo": "24E113B87",
    "dob": "8/6/2006",
    "photo": "https://drive.google.com/thumbnail?id=1bfVHk4mGquvKMGqeXgn1P3b5cxbuI4uF&sz=w1000"
  },
  {
    "id": "120",
    "name": "Sunetra Pandey",
    "team": "Technical",
    "designation": "Core",
    "email": "pandeysunetra7@gmail.com",
    "phone": "24E116B00",
    "linkedin": "https://www.linkedin.com/in/sunetra-pandey-500278323/",
    "instagram": "https://www.instagram.com/__.sunetra/",
    "branch": "CSE (CYSC)",
    "year": "3rd year",
    "regNo": "24E116B00",
    "dob": "2/3/2006",
    "photo": "https://drive.google.com/thumbnail?id=16JyZeP38fbIXoKFyOJelC2lHYVbmda-F&sz=w1000"
  },
  {
    "id": "121",
    "name": "Shubham Modi",
    "team": "Technical",
    "designation": "Core",
    "email": "shubhammodi2003@gmail.com",
    "phone": "9102266990",
    "linkedin": "www.linkedin.com/in/shubham-modi-203141253",
    "instagram": "https://www.instagram.com/modi_shubham2709/",
    "branch": "CSIT",
    "year": "4th year",
    "regNo": "2341013225",
    "dob": "9/27/2003",
    "photo": "https://drive.google.com/thumbnail?id=1GRHaOdcZapgqe6BW6XZPcehOWUXdYqGf&sz=w1000"
  }
];
